# Generated by Django 3.0.6 on 2020-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_posts_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(default='default_profile.png', upload_to='Profilepics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='default_cover.png', upload_to='coverpics/'),
        ),
    ]
