# Generated by Django 3.0.1 on 2020-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Images',
            field=models.ImageField(default='default.png', upload_to='Uploaded_pics'),
            preserve_default=False,
        ),
    ]
