# Generated by Django 3.0.1 on 2020-06-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_posts_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Images',
        ),
    ]
